// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbG34vH01XOV94vVJi66fuLeqKJgzGZ1U',
    appId: '1:546603438794:web:ad998caf51551bb7ca9a33',
    messagingSenderId: '546603438794',
    projectId: 'agapay-hackathon',
    authDomain: 'agapay-hackathon.firebaseapp.com',
    storageBucket: 'agapay-hackathon.firebasestorage.app',
    measurementId: 'G-SQC8XMWJ5X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV2FHp86L0JG39celmlCtwiAnqxuFWnr4',
    appId: '1:546603438794:android:c0d681334a4e0425ca9a33',
    messagingSenderId: '546603438794',
    projectId: 'agapay-hackathon',
    storageBucket: 'agapay-hackathon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVilSojXx5RjCWNTcRJNeFRsDb4lsF9K4',
    appId: '1:546603438794:ios:f3c5ec1b95b388ddca9a33',
    messagingSenderId: '546603438794',
    projectId: 'agapay-hackathon',
    storageBucket: 'agapay-hackathon.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbG34vH01XOV94vVJi66fuLeqKJgzGZ1U',
    appId: '1:546603438794:web:5bd41b73cd560ec2ca9a33',
    messagingSenderId: '546603438794',
    projectId: 'agapay-hackathon',
    authDomain: 'agapay-hackathon.firebaseapp.com',
    storageBucket: 'agapay-hackathon.firebasestorage.app',
    measurementId: 'G-Q06ZN54GQ4',
  );
}
